version: '3.9'
services:
    php:
        build: ./docker/php
        container_name: php
        volumes:
            - ./public:/var/www/html
#        env_file:
#            - .env
        networks:
            - app-network
    
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./public:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/logs:/var/log/nginx
        networks:
            - app-network
        
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1111
            MYSQL_DATABASE: test
        ports:
            - "3307:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/local.cnf:/etc/mysql/conf.d/local.cnf
        networks:
            - app-network
    
#    postgres:
#        image: postgres:13
#        container_name: postgres
#        environment:
#            POSTGRES_DB: test
#            POSTGRES_USER: postgres
#            POSTGRES_PASSWORD: 1111
#        env_file:
#            - .env
#        volumes:
#            - ./docker/postgres-data:/var/lib/postgresql/data
#        networks:
#            - app-network
    
#    redis:
#        image: redis:latest
#        container_name: redis
#        ports:
#            - "6379:6379"
#        volumes:
#            - ./docker/redis-data:/data
#        networks:
#            - app-network

networks:
    app-network:
        driver: bridge